version: '3'

services:
  # Elastic Cluster
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - docker
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - docker
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - docker

  # Head Plugin
  headPlugin:
    image: 'mobz/elasticsearch-head:5'
    container_name: head
    ports:
      - '9100:9100'
    networks:
      - docker
  
  # Kibana
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.2.4
    volumes:
      - ./kibana/config/kibana.yml:/etc/kibana/kibana.yml
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    tty: true
    networks:
      - docker
  
  # Cerebro
  cerebro:
    container_name: cerebro
    image: yannart/cerebro:0.5.0
    volumes:
      - ./cerebro/config/conf:/opt/cerebro/conf
      - ./cerebro/logs:/opt/cerebro/logs
    depends_on:
      - elasticsearch
    ports:
      - 9000:9000
    tty: true
    networks:
      - docker
  
  # Logstash
  logstash:
    container_name: logstash
    image: logstash:6.8.3
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    ports:
      - 9600:9600
    networks:
      - docker

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  docker:
    driver: bridge    
